---
include:
  - project: veepee/vptech/ci-cd/markdown-lint
    ref: 1-latest
    file: gitlab-ci.yml
  - project: veepee/vptech/ci-cd/python-build
    ref: 3-latest
    file: gitlab-ci.yml
  - project: veepee/vptech/ci-cd/semantic-release
    ref: 2-latest
    file: gitlab-ci.yml
  - project: veepee/vptech/ci-cd/python-lint
    ref: 3-latest
    file: gitlab-ci.yml

stages:
  - lint
  - release
  - publish-python

variables:
  PYTHON_MODULE: "quality_toolkit"
  PYTHON_LINT_EXTRA: "-f json --rcfile=.pylintrc"
  APP_NAME: quality-toolkit
  SEMANTIC_CONFIG_FILE: python
  PYTHON_VEEPEE_REGISTRY_ENABLED: "false"
  REGISTRY_PYPI_REPO: "https://test.pypi.org/legacy/"
  PYTHON_VERSION: "3.10"