---
include:
  - project: veepee/vptech/ci-cd/markdown-lint
    ref: 1.1.3
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 4.0.0
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/python-build
    ref: 2.4.1
    file: gitlab-ci.yml

variables:
  PYTHON_MODULE: quality_toolkit
  APP_NAME: quality-toolkit
  SEMANTIC_CONFIG_FILE: python
  PYTHON_VEEPEE_REGISTRY_ENABLED: "false"
  REGISTRY_PYPI_REPO: "https://test.pypi.org/legacy/"

stages:
  - lint
  - release
  - build
  - publish-python

lint:python:
  stage: lint
  image: docker.registry.vptech.eu/vptech/python:latest
  script:
    - pip install pylint
    - if [ -f "requirements.txt" ]; then pip install -r "requirements.txt"; else echo "No requirements found"; fi
    - pylint -f json --rcfile=.pylintrc $PYTHON_MODULE

.debian:dependencies:
  variables:
    CRYPTOGRAPHY_DONT_BUILD_RUST: 1

publish-feature:python:
  extends:
    - .python-publish
    - .constraints-python:feature
    - .debian:dependencies

delete-feature:python:
  extends:
    - .constraints-python:feature
    - .debian:dependencies

publish-release:python:
  extends:
    - .python-publish
    - .constraints-python:master
    - .debian:dependencies
