---
include:
  - project: veepee/vptech/sre/iac/ci-cd/markdown-lint
    ref: 1.4.0
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 3.2.1
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/python-build
    ref: 2.0.1
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/python-lint
    ref: 1.1.3
    file: gitlab-ci.yml

variables:
  PYTHON_MODULE: quality_toolkit
  APP_NAME: quality-toolkit
  SEMANTIC_CONFIG_FILE: python
  PYTHON_VEEPEE_REGISTRY_ENABLED: "false"
  REGISTRY_PYPI_REPO: "https://test.pypi.org/legacy/"

stages:
  - lint
  - release
  - build
  - publish-python

lint:python:
  before_script:
    # for pgsql
    - apk add --no-cache postgresql-libs
    - apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev
  variables:
    CRYPTOGRAPHY_DONT_BUILD_RUST: 1

.debian:dependencies:
  variables:
    CRYPTOGRAPHY_DONT_BUILD_RUST: 1

publish-feature:python:
  extends:
    - .python-publish
    - .constraints-python:feature
    - .debian:dependencies

delete-feature:python:
  extends:
    - .constraints-python:feature
    - .debian:dependencies

publish-release:python:
  extends:
    - .python-publish
    - .constraints-python:master
    - .debian:dependencies
