---
include:
  - project: veepee/vptech/ci-cd/markdown-lint
    ref: 1-latest
    file: gitlab-ci.yml
  - project: veepee/vptech/ci-cd/python-build
    ref: 2-latest
    file: gitlab-ci.yml
  - project: veepee/vptech/ci-cd/semantic-release
    ref: 2-latest
    file: gitlab-ci.yml
  - project: veepee/vptech/ci-cd/python-lint
    ref: 1-latest
    file: gitlab-ci.yml

stages:
  - lint
  - release
  - publish-python

variables:
  PYTHON_MODULE: quality_toolkit
  APP_NAME: quality-toolkit
  SEMANTIC_CONFIG_FILE: python
  PYTHON_VEEPEE_REGISTRY_ENABLED: "false"
  REGISTRY_PYPI_REPO: "https://test.pypi.org/legacy/"

.debian:dependencies:
  variables:
    CRYPTOGRAPHY_DONT_BUILD_RUST: 1

publish-feature:python:
  extends:
    - .python-publish
    - .constraints-python:feature
    - .debian:dependencies

delete-feature:python:
  extends:
    - .constraints-python:feature
    - .debian:dependencies

publish-release:python:
  extends:
    - .python-publish
    - .constraints-python:main
    - .debian:dependencies
